export const FETCH_FURNITURE = 'FETCH_FURNITURE';
export const FETCH_FURNITURE_SUCCESS = 'FETCH_FURNITURE_SUCCESS';
export const FETCH_FURNITURE_FAILURE = 'FETCH_FURNITURE_FAILURE';
export const FETCH_ALL_FURNITURE = 'FETCH_ALL_FURNITURE';
export const FETCH_ALL_FURNITURE_SUCCESS = 'FETCH_ALL_FURNITURE_SUCCESS';

export const FETCH_SALE = 'FETCH_SALE';
export const FETCH_SALE_SUCCESS = 'FETCH_SALE_SUCCESS';
export const FETCH_SALE_FAILURE = 'FETCH_SALE_FAILURE';

export const FETCH_BUYER = 'FETCH_BUYER';
export const FETCH_BUYER_SUCCESS = 'FETCH_BUYER_SUCCESS';
export const FETCH_BUYER_FAILURE = 'FETCH_BUYER_FAILURE';
export const FETCH_BUYER_BY_ID = 'FETCH_BUYER_BY_ID';
export const FETCH_BUYER_BY_ID_SUCCESS = 'FETCH_BUYER_BY_ID_SUCCESS';
// export const FETCH_BUYER_BY_ID_FAILURE = 'FETCH_BUYER_BY_ID_FAILURE';
export const FETCH_ALL_BUYERS = 'FETCH_ALL_BUYERS';
export const FETCH_ALL_BUYERS_SUCCESS = 'FETCH_ALL_BUYERS_SUCCESS';


export const FETCH_CONTRACT = 'FETCH_CONTRACT';
export const FETCH_CONTRACT_SUCCESS = 'FETCH_CONTRACT_SUCCESS';
export const FETCH_CONTRACT_FAILURE = 'FETCH_CONTRACT_FAILURE';